import os
import matplotlib.pyplot as plt
import numpy as np

# ==================================================
# plot (f) of Figs. 3, 6, and 7
# domain-averaged background RMSEs of the tested filters
#
# The RMSE *.npz files used by this script are generated by
# the save_rmse_b() in L96enkf.py and must be stored 
# in the ./rmse_npz directory before running this script.
# ==================================================

def plot_overlay_rmse_b(
    npz_paths,
    labels=None,
    step_min=None,
    step_max=None,
    save=False,
    fname="overlay_rmse.png",
    tick_size=12
):
    if labels is None:
        labels = [os.path.basename(p).replace(".npz", "") for p in npz_paths]

    colors = ["tab:pink", "tab:blue", "tab:orange", "tab:green", "tab:red"]

    fig, ax = plt.subplots(figsize=(12, 3.2))

    for i, (path, lab) in enumerate(zip(npz_paths, labels)):
        d = np.load(path)

        step = d["step"].astype(int)
        rmse_b = d["rmse_b"].astype(float)

        mask = np.ones_like(step, dtype=bool)

        if step_min is not None:
            mask &= step >= step_min

        if step_max is not None:
            mask &= step <= step_max

        ax.plot(
            step[mask],
            rmse_b[mask],
            label=lab,
            linewidth=1.2,
            color=colors[i % len(colors)]
        )

    ax.set_xlabel("Time step", fontsize=14)
    ax.set_ylabel("RMSE", fontsize=14)

    ax.tick_params(
        axis="both",
        which="major",
        labelsize=tick_size
    )

    ax.grid(True, alpha=0.3)
    ax.legend(
        loc="upper right",
        fontsize=10
    )

    fig.tight_layout()

    if save:
        output_dir = os.path.dirname(fname)

        if output_dir:
            os.makedirs(output_dir, exist_ok=True)

        fig.savefig(
            fname,
            dpi=400,
            bbox_inches="tight"
        )
        print(f"[Saved] {fname}")

    plt.show()
    plt.close(fig)


# settings =========================

num = 2    # CASE number

paths = [
    f"./rmse_npz/CASE{num}_LETKF_Ne50_rmse_b.npz",
    f"./rmse_npz/CASE{num}_GETKF_Ne50_rmse_b.npz",
    f"./rmse_npz/CASE{num}_LMETKF_noR_Ne50_rmse_b.npz",
    f"./rmse_npz/CASE{num}_LMETKF_R_Ne50_rmse_b.npz",
    f"./rmse_npz/CASE{num}_LMETKF_Z_Ne50_rmse_b.npz",
]

labels = [
    "LETKF",
    "GETKF",
    "LMETKF-noR",
    "LMETKF-R",
    "LMETKF-Z"
]


# plot =========================

plot_overlay_rmse_b(
    npz_paths=paths,
    labels=labels,
    step_min=3000,
    step_max=4000,
    save=True,
    fname=f"./fig_rmse/CASE{num}_overlay_rmse_3000_4000.png",
    tick_size=11
)